name = "VanillaOptimized"
author = "Soikr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f837c7f28d13c20bc942a27d9bd10a1a1ce789cf1181696a7e1d5b9ce8e301b0"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
