name = "SimpleModpack"
author = "Soikr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93d2142a9205688a620e6973e27dd4c6b3872d09f275fa6ec532527639afc5bf"

[versions]
fabric = "0.16.13"
minecraft = "1.20.1"
