name = "SimpleModpack"
author = "Soikr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ceb8041da1778ebd031d18d5e071f789e36383e46835eed2aef1c5e5c06bd89b"

[versions]
fabric = "0.16.13"
minecraft = "1.20.1"
