name = "VanillaOptimized"
author = "Soikr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5598455955da360818aa23abaa1f73174c62ec3e6b54ce0113541040ec59889"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
