name = "SimpleModpack"
author = "Soikr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbd494283ec3dff0b7f76ed1271c4eccd0b22b50b29b1a77a5ba58c976292a81"

[versions]
fabric = "0.16.13"
minecraft = "1.20.1"
