name = "SimpleModpack"
author = "Soikr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2b0172400bdf7776810f904b584089f33541f41a7d5c923bfcd3095d8dda08b"

[versions]
fabric = "0.16.13"
minecraft = "1.20.1"
