name = "VanillaOptimized"
author = "Soikr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67063005ba19b3071a6b9446726e5ba49677dd1aa1d0bfccdc120595cf33e1b1"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
