name = "VanillaOptimized"
author = "Soikr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "438b6fddd521b5f6ef7963363b88d95a4fb146368521b87af127046a28083278"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
