[teleports]
  enableCooldowns = true
  warpRequirements = ["[is_not_interdimensional] scaled_add_xp_cost(distance, 0)", "[is_interdimensional] add_xp_cost(27)", "[source_is_warp_plate] multiply_xp_cost(0)", "[target_is_global] multiply_xp_cost(0)", "min_xp_cost(0)", "max_xp_cost(27)", "[source_is_inventory_button] add_cooldown(inventory_button, 300)"]

[worldGen]
  chunksBetweenWildWaystones = 0
  enableCosts = false
